### ISSUE TITLE
❔ Requête non identiques isee.nc vs data.gouv.nc ❔ 

### ISSUE THREAD

**Issue by adriens** [adriens/ridetnc-api#1]
# Description

Selon que l'on requête sur [isee.nc](https://avisridet.isee.nc/) ou [data.gouv.nc](https://data.gouv.nc/explore/dataset/entreprises-actives-au-ridet/api/?disjunctive.libelle_formjur&disjunctive.code_ape&disjunctive.libelle_naf&disjunctive.section_naf&disjunctive.libelle_section_naf&disjunctive.libelle_commune&disjunctive.hors_nc&disjunctive.province&disjunctive.employeuse&refine.rid7=0132720), on obtient pas les mêmes résultats : 

Avec le code `0132720` : 

- Un hit unique sur [data.gouv.nc](https://data.gouv.nc/explore/dataset/entreprises-actives-au-ridet/api/?disjunctive.libelle_formjur&disjunctive.code_ape&disjunctive.libelle_naf&disjunctive.section_naf&disjunctive.libelle_section_naf&disjunctive.libelle_commune&disjunctive.hors_nc&disjunctive.province&disjunctive.employeuse&refine.rid7=0132720) : 
```json
"records":[

    {
        "datasetid":"entreprises-actives-au-ridet",
        "recordid":"71c21b7f85eede04597d3a11fc9d5a507d2f41ba",
        "fields":{
            "province":"province Sud",
            "libelle_section_naf":"Information et communication",
            "code_formjur":"4140",
            "libelle_formjur":"Etablissement public local à caractère industriel ou commercial",
            "code_ape":"6110Z",
            "code_commune":"18",
            "denomination":"OFFICE DES POSTES ET TELECOMMUNICATIONS",
            "libelle_division_naf":"Télécommunications",
            "libelle_commune":"Nouméa",
            "section_naf":"J",
            "employeuse":"non",
            "rid7":"0132720",
            "libelle_naf":"Télécommunications filaires",
            "division_naf":"61"
        }
        ,
        "record_timestamp":"2021-07-23T05:39:18.898000+00:00"
    }

]
,
```
- sur [isee.nc](https://avisridet.isee.nc/) plusieurs hits : 
![image](https://user-images.githubusercontent.com/5235127/128774307-96f903ab-4756-4535-b55a-fa1f93913d7d.png)

**Comment by houysy** [comment]
Adrien, merci pour ton partage.
Le résultat est différent car dans le 1er cas, tu requêtes la[ liste des entreprises (RID)](https://data.gouv.nc/explore/dataset/entreprises-actives-au-ridet/table/?disjunctive.libelle_formjur&disjunctive.code_ape&disjunctive.libelle_naf&disjunctive.section_naf&disjunctive.libelle_section_naf&disjunctive.libelle_commune&disjunctive.hors_nc&disjunctive.province&disjunctive.employeuse&q=0132720), et dans le 2ème cas, tu requêtes sur la liste des établissements pour cette entreprise.
Depuis, sur data.gouv.nc, l'ISEE a également publié le [jeu de données des établissements](https://data.gouv.nc/explore/dataset/etablissements-actifs-au-ridet/table/?disjunctive.libelle_formjur&disjunctive.code_ape&disjunctive.libelle_naf&disjunctive.section_naf&disjunctive.libelle_section_naf&disjunctive.libelle_commune&disjunctive.hors_nc&disjunctive.province&q=0132720)

**Comment by adriens** [comment]
AHhhh, yes, merci pour ton super commentaire... et sur Github ❣️ ❣️ ❣️ 

J'adore !!! Merci beaucoup pour la collaboration, t'es au top 😺
